apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/poetic-brace-430620-b4/store-registry/payment-ms
          name: payments-ms
          env:
            - name: PORT
              value: '3000'
            - name: NATS_SERVERS
              value: 'nats://nats'
            - name: STRIPE_SUCCESS_URL
              value: 'https://shop-thec.netlify.app/#/payments/success'
            - name: STRIPE_CANCEL_URL
              value: 'https://shop-thec.netlify.app/#/payments/cancelled'
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secret
                  key: stripe_secret
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secret
                  key: stripe_endpoint_secret
          resources: {}
status: {}
